<?php
/**
 * Private message module
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license         GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
 * @package         pm
 * @since           2.3.0
 * @author          Jan Pedersen
 * @author          Taiwen Jiang <phppp@users.sourceforge.net>
 * @version         $Id: xoops_version.php 12593 2014-06-14 16:04:02Z beckmi $
 */

/**
 * This is a temporary solution for merging XOOPS 2.0 and 2.2 series
 * A thorough solution will be available in XOOPS 3.0
 *
 */

$modversion                   = array();
$modversion['name']           = _IPV4_MI_NAME;
$modversion['version']        = 1.10;
$modversion['description']    = _IPV4_MI_DESC;
$modversion['author']         = "Simon Antony Roberts";
$modversion['credits']        = "Chronolabs";
$modversion['help']           = 'page=help';
$modversion['license']        = 'GNU GPL 2.0 or later';
$modversion['license_url']    = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['image']          = "images/logo.png";
$modversion['dirname']        = "ipv4";
$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16']        = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion["module_status"]       = "Final";
$modversion['release_date']        = '2015/11/23';
$modversion["module_website_url"]  = "http://labs.coop/";
$modversion["module_website_name"] = "Chronolabs";
$modversion['min_php']             = '5.3.7';
$modversion['min_xoops']           = "2.5.7";
$modversion['min_admin']           = '1.1';
$modversion['min_db']              = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7'
);

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 0;

// Admin things
$modversion['hasAdmin']   = 0;
$modversion['adminindex'] = "admin/admin.php";
$modversion['adminmenu']  = "admin/menu.php";

// Mysql file
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Table
//$modversion['tables'][0] = "pm_messages";

// Scripts to run upon installation or update
//$modversion['onInstall'] = "include/install.php";
//$modversion['onUpdate']  = "include/update.php";

// Templates
$modversion['templates']                   = array();
$modversion['templates'][1]['file']        = 'ipv4_index.tpl';
$modversion['templates'][1]['description'] = '';
//$modversion['templates'][4]['file'] = 'pm_lookup.tpl';
//$modversion['templates'][4]['description'] = '';

// Menu
$modversion['hasMain'] = 1;

$modversion['config']   = array();
$modversion['config'][] = array(
    'name'        => 'htaccess',
    'title'       => '_IPV4_MI_HTACCESS',
    'description' => '_IPV4_MI_HTACCESS_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => false
);

$modversion['config'][] = array(
    'name'        => 'base_url',
    'title'       => '_IPV4_MI_BASEURL',
    'description' => '_IPV4_MI_BASEURL_DESC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => "ipv4"
);

$modversion['config'][] = array(
    'name'        => 'end_url',
    'title'       => '_IPV4_MI_ENDURL',
    'description' => '_IPV4_MI_ENDURL_DESC',
    'formtype'    => 'textbox',
    'valuetype'   => 'text',
    'default'     => ".html"
);
